import os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
with open("app.py", encoding="utf-8") as f:
    data = f.read()
marker = "# ---- Main ----"
idx = data.find(marker)
if idx == -1:
    marker = "if __name__"
    idx = data.find(marker)
print(f"Insert at byte {idx}")
new = []
new.append("")
new.append("# ====== Week 7: Image Capture (Precaptured Only) ======")
new.append("")
new.append("@app.route('/api/capture_image', methods=['POST'])")
new.append("def api_capture_image():")
new.append('    """Return a random precaptured image as base64 data URI."""')
new.append("    import base64, glob, os, random")
new.append("    from datetime import datetime")
new.append("    source = 'precaptured'")
new.append("    precaptured_dir = os.path.join(os.path.dirname(__file__), 'precaptured')")
new.append("    try:")
new.append("        if not os.path.isdir(precaptured_dir):")
new.append("            return jsonify({'success':False,'error':'dir not found','source':source}),500")
new.append("        image_files = []")
new.append("        for ext in ('*.jpg','*.jpeg','*.png','*.bmp'):")
new.append("            image_files.extend(glob.glob(os.path.join(precaptured_dir, ext)))")
new.append("        if not image_files:")
new.append("            return jsonify({'success':False,'error':'no images','source':source}),404")
new.append("        chosen = random.choice(image_files)")
new.append("        with open(chosen, 'rb') as f:")
new.append("            raw = f.read()")
new.append("        img_b64 = base64.b64encode(raw).decode('utf-8')")
new.append("        ext = os.path.splitext(chosen)[1].lower()")
new.append("        mime_map = {'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.bmp':'image/bmp'}")
new.append("        mime = mime_map.get(ext, 'image/jpeg')")
new.append("        data_uri = f'data:{mime};base64,{img_b64}'")
new.append("        try:")
new.append("            conn = get_db()")
new.append("            conn.execute('INSERT INTO captured_images (filename, source, created_at) VALUES (?,?,?)',")
new.append("                (os.path.basename(chosen), source, datetime.now().isoformat()))")
new.append("            conn.commit(); conn.close()")
new.append("        except Exception:")
new.append("            pass")
new.append("        return jsonify({'success':True,'image':data_uri,'source':source})")
new.append("    except Exception as e:")
new.append("        log.error('Capture error: %s', e)")
new.append("        return jsonify({'success':False,'error':str(e),'source':source}),500")
new.append("")
new_code = "\n".join(new)
new_data = data[:idx] + new_code + "\n\n" + data[idx:]
with open("app.py", "w", encoding="utf-8") as f:
    f.write(new_data)
print("Done. Validating...")
import ast
ast.parse(open("app.py", encoding="utf-8").read())
print("Syntax OK!")